spring:
  application:
    name: leaderboard-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/leaderboarddb
    username: leaderboarddb
    password: leaderboarddb
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: false
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

logging:
  level:
    root: INFO      # For development, set to DEBUG
    org.springframework.web: INFO
    com.example.demo: DEBUG